"""clean schema

Revision ID: 0d69337bf5d6
Revises: d4bab5ea20c9
Create Date: 2026-06-14 00:12:13.678614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d69337bf5d6'
down_revision: Union[str, Sequence[str], None] = 'd4bab5ea20c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('otp_id', sa.Integer(), nullable=False),
    sa.Column('otp_phone_number', sa.String(length=15), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('otp_id')
    ) # ### end Alembic commands ###
    op.create_index(op.f('ix_otp_codes_otp_id'), 'otp_codes', ['otp_id'], unique=False)
    
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_phone_number', sa.String(), nullable=True),
    sa.Column('user_citizenship_number', sa.String(), nullable=True),
    sa.Column('user_provience', sa.String(), nullable=True),
    sa.Column('user_district', sa.String(), nullable=True),
    sa.Column('user_municipality', sa.String(), nullable=True),
    sa.Column('user_ward_number', sa.Integer(), nullable=True),
    sa.Column('user_role', sa.Enum('SuperAdmin', 'Citizen', 'WardChairperson', 'WardSecretary', 'DataValidationOfficer', name='roleschema'), nullable=True),
    sa.Column('reated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True), # ⚠️ Note: Check if model spelling should be "created_at"
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_citizenship_number'), 'users', ['user_citizenship_number'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.create_index(op.f('ix_users_user_phone_number'), 'users', ['user_phone_number'], unique=True)
    
    op.create_table('users_verify',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_phone_number', sa.String(), nullable=True),
    sa.Column('user_citizenship_number', sa.String(), nullable=True),
    sa.Column('user_provience', sa.String(), nullable=True),
    sa.Column('user_district', sa.String(), nullable=True),
    sa.Column('user_municipality', sa.String(), nullable=True),
    sa.Column('user_ward_number', sa.Integer(), nullable=True),
    sa.Column('user_role', sa.Enum('SuperAdmin', 'Citizen', 'WardChairperson', 'WardSecretary', 'DataValidationOfficer', name='roleschema'), nullable=True),
    sa.Column('user_status', sa.Enum('Pending', 'Approved', 'Rejected', name='registrationstatus'), nullable=True),
    sa.Column('reated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True), # ⚠️ Note: Check if model spelling should be "created_at"
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_verify_user_citizenship_number'), 'users_verify', ['user_citizenship_number'], unique=True)
    op.create_index(op.f('ix_users_verify_user_id'), 'users_verify', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_verify_user_name'), 'users_verify', ['user_name'], unique=True)
    op.create_index(op.f('ix_users_verify_user_phone_number'), 'users_verify', ['user_phone_number'], unique=True)
    
    op.create_table('ward',
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('ward_no', sa.Integer(), nullable=False),
    sa.Column('word_municipality', sa.String(length=100), nullable=False), # ⚠️ Note: Check if spelling should be "ward_municipality"
    sa.Column('word_district', sa.String(length=100), nullable=False),     # ⚠️ Note: Check if spelling should be "ward_district"
    sa.Column('ward_province', sa.String(length=50), nullable=False),
    sa.Column('ward_contact_number', sa.String(length=50), nullable=False),
    sa.Column('ward_email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ward_id'),
    sa.UniqueConstraint('ward_email')
    )
    
    op.create_table('birth_registration',
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('register_ward_id', sa.UUID(), nullable=False),
    sa.Column('register_submitted_by', sa.Integer(), nullable=False), # ✅ CHANGED FROM sa.UUID() TO sa.Integer() TO MATCH USERS TABLE
    sa.Column('register_status', sa.Enum('DRAFT', 'SUBMITTED', 'DOCUMENT_REQUESTED', 'APPROVED', 'CERTIFICATE_ISSUED', 'REJECTED', name='registrationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['register_submitted_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['register_ward_id'], ['ward.ward_id'], ),
    sa.PrimaryKeyConstraint('registration_id')
    )
    
    op.create_table('child',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('child_full_name', sa.String(length=100), nullable=True),
    sa.Column('child_gender', sa.Enum('MALE', 'FEMALE', 'OTHERS', name='gendertype'), nullable=False),
    sa.Column('child_dob_bs', sa.String(length=50), nullable=False),
    sa.Column('child_time_of_birth', sa.String(), nullable=True),
    sa.Column('child_province', sa.String(length=100), nullable=True),
    sa.Column('child_district', sa.String(length=100), nullable=True),
    sa.Column('child_municipality', sa.String(length=100), nullable=True),
    sa.Column('child_ward_no', sa.Integer(), nullable=True),
    sa.Column('child_birth_kind', sa.Enum('SINGLE', 'TWIN', 'TRIPLET_OR_MORE', name='birthkindtype'), nullable=False),
    sa.Column('child_weight_kg', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('child_id')
    )
    
    op.create_table('nominee',
    sa.Column('nominee_id', sa.UUID(), nullable=False),
    sa.Column('nominee_registration_id', sa.UUID(), nullable=True),
    sa.Column('nominee_full_name', sa.String(length=100), nullable=True),
    sa.Column('nominee_citizenship_no', sa.String(length=50), nullable=True),
    sa.Column('nominee_address', sa.Text(), nullable=True),
    sa.Column('nominee_contact_no', sa.String(length=20), nullable=True),
    sa.Column('nominee_witness_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nominee_registration_id'], ['birth_registration.registration_id'], ),
    sa.PrimaryKeyConstraint('nominee_id')
    )
    
    op.create_table('parent',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('parent_type', sa.Enum('FATHER', 'MOTHER', name='parenttype'), nullable=False),
    sa.Column('parrent_citizenship_no', sa.String(length=50), nullable=False), # ⚠️ Note: Check if spelling should be "parent_citizenship_no"
    sa.Column('parent_nid_no', sa.String(length=50), nullable=False),
    sa.Column('parent_occupation', sa.String(length=100), nullable=True),
    sa.Column('parent_nationality', sa.String(length=100), nullable=False),
    sa.Column('parent_contact_no', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id')
    )
    
    op.create_table('reject',
    sa.Column('reject_id', sa.UUID(), nullable=False),
    sa.Column('reject_text', sa.Text(), nullable=True),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reject_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reject')
    op.drop_table('parent')
    op.drop_table('nominee')
    op.drop_table('child')
    op.drop_table('birth_registration')
    op.drop_table('ward')
    op.drop_index(op.f('ix_users_verify_user_phone_number'), table_name='users_verify')
    op.drop_index(op.f('ix_users_verify_user_name'), table_name='users_verify')
    op.drop_index(op.f('ix_users_verify_user_id'), table_name='users_verify')
    op.drop_index(op.f('ix_users_verify_user_citizenship_number'), table_name='users_verify')
    op.drop_table('users_verify')
    op.drop_index(op.f('ix_users_user_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_user_citizenship_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_codes_otp_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
   