"""create a user table

Revision ID: 0e48d6622da2
Revises: 
Create Date: 2026-06-10 12:48:10.171387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e48d6622da2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_phone_number', sa.String(), nullable=True),
    sa.Column('user_citizenship_number', sa.String(), nullable=True),
    sa.Column('user_provience', sa.String(), nullable=True),
    sa.Column('user_district', sa.String(), nullable=True),
    sa.Column('user_municipality', sa.String(), nullable=True),
    sa.Column('user_ward_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_citizenship_number'), 'users', ['user_citizenship_number'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.create_index(op.f('ix_users_user_phone_number'), 'users', ['user_phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_user_citizenship_number'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
