"""add tax 3

Revision ID: 12d1e1f5a2c9
Revises: 9f37bba17734
Create Date: 2026-08-02 02:36:10.247323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d1e1f5a2c9'
down_revision: Union[str, Sequence[str], None] = '9f37bba17734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('base_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tax_assessment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('tax_type', sa.Enum('PROPERTY', 'HOUSE_RENT', 'BUSINESS', name='taxtype'), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=10), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('penalty_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ASSESSED', 'PAID', 'OVERDUE', 'DISPUTED', name='taxassessmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['ward.ward_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'tax_type', 'fiscal_year', name='uq_assessment_record_year')
    )
    op.create_index(op.f('ix_tax_assessment_record_id'), 'tax_assessment', ['record_id'], unique=False)
    op.create_table('tax_import_batch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('tax_type', sa.Enum('PROPERTY', 'HOUSE_RENT', 'BUSINESS', name='taxtype'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'REVIEW', 'COMMITTED', name='importbatchstatus'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['ward.ward_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ward_tax_rate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('tax_type', sa.Enum('PROPERTY', 'HOUSE_RENT', 'BUSINESS', name='taxtype'), nullable=False),
    sa.Column('property_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INSTITUTIONAL', 'AGRICULTURAL', 'INDUSTRIAL', name='propertytype'), nullable=True),
    sa.Column('construction_type', sa.Enum('RCC', 'SEMI_PUCCA', 'MUD_BONDED', 'TIN_ROOF', name='constructiontype'), nullable=True),
    sa.Column('location_zone', sa.Enum('MAIN_ROAD', 'SUB_ROAD', 'INTERIOR', name='locationzone'), nullable=True),
    sa.Column('business_scale_tier', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='businessscaletier'), nullable=True),
    sa.Column('rate_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fiscal_year', sa.String(length=10), nullable=False),
    sa.Column('effective_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['ward.ward_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('scale_tier', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='businessscaletier'), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('survey_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ASSESSED', 'DISPUTED', 'CORRECTED', name='taxrecordstatus'), nullable=False),
    sa.Column('dispute_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['business_category.id'], ),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entered_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['tax_import_batch.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['ward.ward_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('property_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('lalpurja_number', sa.String(length=100), nullable=True),
    sa.Column('land_area_sqm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('built_up_area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('property_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INSTITUTIONAL', 'AGRICULTURAL', 'INDUSTRIAL', name='propertytype'), nullable=False),
    sa.Column('construction_type', sa.Enum('RCC', 'SEMI_PUCCA', 'MUD_BONDED', 'TIN_ROOF', name='constructiontype'), nullable=True),
    sa.Column('location_zone', sa.Enum('MAIN_ROAD', 'SUB_ROAD', 'INTERIOR', name='locationzone'), nullable=False),
    sa.Column('number_of_floors', sa.Integer(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('survey_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ASSESSED', 'DISPUTED', 'CORRECTED', name='taxrecordstatus'), nullable=False),
    sa.Column('dispute_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entered_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['tax_import_batch.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['ward.ward_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lalpurja_number')
    )
    op.create_table('tax_dispute',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'RESOLVED', name='taxdisputestatus'), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['tax_assessment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'ESEWA', 'KHALTI', 'CONNECT_IPS', name='taxpaymentmethod'), nullable=False),
    sa.Column('receipt_no', sa.String(length=100), nullable=False),
    sa.Column('paid_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['tax_assessment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_no')
    )
    op.create_table('rental_unit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('unit_type', sa.Enum('SINGLE_ROOM', 'FLAT', 'SHOP', 'FULL_HOUSE', 'FLOOR', name='rentalunittype'), nullable=False),
    sa.Column('number_of_rooms', sa.Integer(), nullable=True),
    sa.Column('monthly_rent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('survey_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entered_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['property_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_import_row',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('matched_citizen_id', sa.Integer(), nullable=True),
    sa.Column('matched_property_id', sa.UUID(), nullable=True),
    sa.Column('match_status', sa.Enum('MATCHED', 'NOT_REGISTERED', 'WARD_MISMATCH', 'DUPLICATE_IN_BATCH', 'INVALID_DATA', name='importrowmatchstatus'), nullable=False),
    sa.Column('import_action', sa.Enum('NEW', 'UPDATE', 'NEEDS_REVIEW', name='importrowaction'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'EDITED', 'REJECTED', name='taximportrowstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['tax_import_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_citizen_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_property_id'], ['property_record.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_import_row')
    op.drop_table('rental_unit')
    op.drop_table('tax_payment')
    op.drop_table('tax_dispute')
    op.drop_table('property_record')
    op.drop_table('business_record')
    op.drop_table('ward_tax_rate')
    op.drop_table('tax_import_batch')
    op.drop_index(op.f('ix_tax_assessment_record_id'), table_name='tax_assessment')
    op.drop_table('tax_assessment')
    op.drop_table('business_category')
    # ### end Alembic commands ###
