"""upgraded alembic head

Revision ID: 13e3aee818b1
Revises: fe843bea651b
Create Date: 2026-06-12 22:06:05.257284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13e3aee818b1'
down_revision: Union[str, Sequence[str], None] = 'fe843bea651b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('province', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('municipality', sa.String(length=100), nullable=False),
    sa.Column('ward_no', sa.Integer(), nullable=False),
    sa.Column('tole', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('ward',
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('ward_no', sa.Integer(), nullable=False),
    sa.Column('municipality', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=50), nullable=False),
    sa.Column('registrar_name', sa.String(length=150), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.PrimaryKeyConstraint('ward_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_account',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('user_role', sa.Enum('CITIZEN', 'WARD_OFFICER', 'REGISTRAR', 'ADMIN', name='userroletype'), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ward_id'], ['ward.ward_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('birth_registration',
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('is_late_registration', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'DOCUMENT_REQUESTED', 'APPROVED', 'CERTIFICATE_ISSUED', 'REJECTED', name='registrationstatus'), nullable=False),
    sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fine_paid', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('verified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('issued_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('fine_amount >= 0', name='chk_fine_non_negative'),
    sa.CheckConstraint('fine_paid = FALSE OR is_late_registration = TRUE', name='chk_fine_paid_only_if_late'),
    sa.ForeignKeyConstraint(['submitted_by'], ['user_account.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['ward.ward_id'], ),
    sa.PrimaryKeyConstraint('registration_id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('certificate',
    sa.Column('cert_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('certificate_no', sa.String(length=100), nullable=False),
    sa.Column('nid_no', sa.String(length=50), nullable=True),
    sa.Column('issued_date_bs', sa.String(length=50), nullable=True),
    sa.Column('issued_date_ad', sa.Date(), nullable=True),
    sa.Column('issued_by', sa.UUID(), nullable=True),
    sa.Column('qr_code_data', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_reason IS NOT NULL', name='chk_revoked_has_reason'),
    sa.ForeignKeyConstraint(['issued_by'], ['user_account.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cert_id'),
    sa.UniqueConstraint('certificate_no'),
    sa.UniqueConstraint('registration_id')
    )
    op.create_table('child',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHERS', name='gendertype'), nullable=False),
    sa.Column('dob_bs', sa.String(length=50), nullable=False),
    sa.Column('dob_ad', sa.Date(), nullable=False),
    sa.Column('time_of_birth', sa.Time(), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('municipality', sa.String(length=100), nullable=True),
    sa.Column('ward_no', sa.Integer(), nullable=True),
    sa.Column('tole', sa.String(length=50), nullable=True),
    sa.Column('birth_kind', sa.Enum('SINGLE', 'TWIN', 'TRIPLET_OR_MORE', name='birthkindtype'), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.CheckConstraint('weight_kg IS NULL OR weight_kg > 0', name='chk_weight_positive'),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('child_id'),
    sa.UniqueConstraint('registration_id')
    )
    op.create_table('document',
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('CITIZENSHIP_FATHER', 'CITIZENSHIP_MOTHER', 'MARRIAGE_CERT', 'RESIDENCE_PROOF', 'IN_MIGRATION_CERT', name='documenttype'), nullable=False),
    sa.Column('file_name', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('file_size_kb IS NULL OR file_size_kb > 0', name='chk_file_size'),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['user_account.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('informant',
    sa.Column('informant_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('citizenship_no', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_no', sa.String(length=20), nullable=True),
    sa.Column('reported_at_bs', sa.String(length=20), nullable=True),
    sa.Column('reported_at_ad', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('informant_id'),
    sa.UniqueConstraint('registration_id')
    )
    op.create_table('nominee',
    sa.Column('nominee_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('citizenship_no', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_no', sa.String(length=20), nullable=True),
    sa.Column('witness_order', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('witness_order IN (1, 2)', name='chk_witness_order'),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nominee_id'),
    sa.UniqueConstraint('registration_id', 'witness_order', name='uq_witness_per_registration')
    )
    op.create_table('parent',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('parent_type', sa.Enum('FATHER', 'MOTHER', name='parenttype'), nullable=False),
    sa.Column('citizenship_no', sa.String(length=50), nullable=False),
    sa.Column('nid_no', sa.String(length=50), nullable=False),
    sa.Column('address_id', sa.UUID(), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('contact_no', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id'),
    sa.UniqueConstraint('registration_id', 'parent_type', name='uq_parent_per_registration')
    )
    op.create_table('workflow_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('status_from', sa.String(length=50), nullable=True),
    sa.Column('status_to', sa.String(length=50), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['user_account.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.drop_index(op.f('ix_users_user_citizenship_number'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_user_phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_codes_otp_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('otp_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('otp_phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('otp_code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('otp_id', name=op.f('otp_codes_pkey'))
    )
    op.create_index(op.f('ix_otp_codes_otp_id'), 'otp_codes', ['otp_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_citizenship_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_provience', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_municipality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_ward_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_role', postgresql.ENUM('SuperAdmin', 'Citizen', 'WardChairperson', 'WardSecretary', 'DataValidationOfficer', name='roleschema'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_user_phone_number'), 'users', ['user_phone_number'], unique=True)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_user_citizenship_number'), 'users', ['user_citizenship_number'], unique=True)
    op.drop_table('workflow_log')
    op.drop_table('parent')
    op.drop_table('nominee')
    op.drop_table('informant')
    op.drop_table('document')
    op.drop_table('child')
    op.drop_table('certificate')
    op.drop_table('birth_registration')
    op.drop_table('user_account')
    op.drop_table('ward')
    op.drop_table('address')
    # ### end Alembic commands ###
