"""add user_status column

Revision ID: 193bfe9922bb
Revises: 924a2d7faa80
Create Date: 2026-06-18 20:26:12.219317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '193bfe9922bb'
down_revision: Union[str, Sequence[str], None] = '924a2d7faa80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'address', 'birth_registration', ['registration_id'], ['registration_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'child', 'birth_registration', ['registration_id'], ['registration_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'nominee', 'birth_registration', ['nominee_registration_id'], ['registration_id'])
    op.create_foreign_key(None, 'reject', 'birth_registration', ['registration_id'], ['registration_id'], ondelete='CASCADE')
    op.add_column('users_verify', sa.Column('user_status', sa.Enum('Pending', 'Approved', 'Rejected', name='registrationstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_verify', 'user_status')
    op.drop_constraint(None, 'reject', type_='foreignkey')
    op.drop_constraint(None, 'nominee', type_='foreignkey')
    op.drop_constraint(None, 'child', type_='foreignkey')
    op.drop_constraint(None, 'address', type_='foreignkey')
    # ### end Alembic commands ###
