"""add ward name

Revision ID: 1aca2d0e844e
Revises: a64741184769
Create Date: 2026-06-16 16:54:05.716242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aca2d0e844e'
down_revision: Union[str, Sequence[str], None] = 'a64741184769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ward', sa.Column('ward_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ward', 'ward_name')
    # ### end Alembic commands ###
