"""your mes

Revision ID: 22fb371af575
Revises: b714c5a897f4
Create Date: 2026-08-03 18:38:49.335820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22fb371af575'
down_revision: Union[str, Sequence[str], None] = 'b714c5a897f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_payment', sa.Column('qr_path', sa.String(length=255), nullable=True))
    op.add_column('tax_payment', sa.Column('pdf_path', sa.String(length=255), nullable=True))
    op.add_column('tax_payment', sa.Column('data_hash', sa.String(length=64), nullable=True))
    op.add_column('tax_payment', sa.Column('receipt_issued_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_payment', 'receipt_issued_at')
    op.drop_column('tax_payment', 'data_hash')
    op.drop_column('tax_payment', 'pdf_path')
    op.drop_column('tax_payment', 'qr_path')
    # ### end Alembic commands ###
