"""update date

Revision ID: 293449b48363
Revises: b65b116cdaa9
Create Date: 2026-07-09 18:56:20.736846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '293449b48363'
down_revision: Union[str, Sequence[str], None] = 'b65b116cdaa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ... other code ...
    op.alter_column(
        'child', 
        'child_dob_bs',
        existing_type=sa.VARCHAR(length=50),
        type_=sa.DateTime(),
        existing_nullable=False,
        postgresql_using="child_dob_bs::timestamp without time zone"  # <-- Add this line!
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('child', 'child_dob_bs',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
