"""add new table otpcode

Revision ID: 2feba12dfb36
Revises: 0de0dbabd6b0
Create Date: 2026-06-10 17:25:42.038515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2feba12dfb36'
down_revision: Union[str, Sequence[str], None] = '0de0dbabd6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('otp_id', sa.Integer(), nullable=False),
    sa.Column('otp_phone_number', sa.String(length=15), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('otp_id')
    )
    op.create_index(op.f('ix_otp_codes_otp_id'), 'otp_codes', ['otp_id'], unique=False)
    op.add_column('users', sa.Column('reated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'reated_at')
    op.drop_index(op.f('ix_otp_codes_otp_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
