"""Initial migration

Revision ID: 32438caf20f2
Revises: a55db0c7ecf0
Create Date: 2026-07-12 02:18:40.801235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32438caf20f2'
down_revision: Union[str, Sequence[str], None] = 'a55db0c7ecf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('ward_type', sa.Enum('METROPOLITAN_CITY', 'SUB_METROPOLITAN_CITY', 'MUNICIPALITY', 'RURAL_MUNICIPALITY', name='municipalitytype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'ward_type')
    # ### end Alembic commands ###
