"""add child nepali name

Revision ID: 3327b58540ce
Revises: 86cde11c7e1b
Create Date: 2026-07-09 01:42:55.190548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3327b58540ce'
down_revision: Union[str, Sequence[str], None] = '86cde11c7e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nominee', sa.Column('nominee_nepali_first_name', sa.String(length=100), nullable=True))
    op.add_column('nominee', sa.Column('nominee_nepali_middle_name', sa.String(length=100), nullable=True))
    op.add_column('nominee', sa.Column('nominee_nepali_last_name', sa.String(length=100), nullable=True))
    op.add_column('parent', sa.Column('parent_nepali_first_name', sa.String(length=100), nullable=True))
    op.add_column('parent', sa.Column('parent_nepali_middle_name', sa.String(length=100), nullable=True))
    op.add_column('parent', sa.Column('parent_nepali_last_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'parent_nepali_last_name')
    op.drop_column('parent', 'parent_nepali_middle_name')
    op.drop_column('parent', 'parent_nepali_first_name')
    op.drop_column('nominee', 'nominee_nepali_last_name')
    op.drop_column('nominee', 'nominee_nepali_middle_name')
    op.drop_column('nominee', 'nominee_nepali_first_name')
    # ### end Alembic commands ###
