"""remove realtionship user3 

Revision ID: 4495f18bfb13
Revises: 9b2cefca9d60
Create Date: 2026-06-17 00:24:59.971202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4495f18bfb13'
down_revision: Union[str, Sequence[str], None] = '9b2cefca9d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('child_province', sa.String(), nullable=True))
    op.drop_column('address', 'child_provience')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('child_provience', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('address', 'child_province')
    # ### end Alembic commands ###
