"""describe parent

Revision ID: 4ff2a9df6c2a
Revises: 59ef755820a8
Create Date: 2026-06-14 12:42:25.160607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff2a9df6c2a'
down_revision: Union[str, Sequence[str], None] = '59ef755820a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('parent_first_name', sa.String(length=100), nullable=True))
    op.add_column('parent', sa.Column('parent_middle_name', sa.String(length=100), nullable=True))
    op.add_column('parent', sa.Column('parent_last_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'parent_last_name')
    op.drop_column('parent', 'parent_middle_name')
    op.drop_column('parent', 'parent_first_name')
    # ### end Alembic commands ###
