"""notice model update

Revision ID: 5642c47643df
Revises: b0730ed5006e
Create Date: 2026-07-04 01:51:40.156140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5642c47643df'
down_revision: Union[str, Sequence[str], None] = 'b0730ed5006e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('notice_title', sa.String(length=255), nullable=False),
    sa.Column('notice_description', sa.Text(), nullable=True),
    sa.Column('notice_ward_id', sa.UUID(), nullable=False),
    sa.Column('notice_type', sa.Enum('PUBLIC', 'TENDER', 'VACANCY', 'TAX', 'MEETING', 'HEALTH', 'EDUCATION', 'DISASTER', 'EVENT', 'OTHER', name='noticetype'), nullable=True),
    sa.Column('notice_status', sa.Enum('DRAFT', 'PUBLISHED', 'EXPIRED', 'ARCHIVED', name='noticestatus'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_ward_id'], ['ward.ward_id'], ),
    sa.PrimaryKeyConstraint('notice_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notices')
    # ### end Alembic commands ###
