"""add remommendaation

Revision ID: 5cb72f74907a
Revises: 4ad1fc0fb711
Create Date: 2026-07-23 19:27:41.380500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb72f74907a'
down_revision: Union[str, Sequence[str], None] = '4ad1fc0fb711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birth_registration', sa.Column('father_citizenship_front_path', sa.String(), nullable=True))
    op.add_column('birth_registration', sa.Column('father_citizenship_back_path', sa.String(), nullable=True))
    op.add_column('birth_registration', sa.Column('mother_citizenship_front_path', sa.String(), nullable=True))
    op.add_column('birth_registration', sa.Column('mother_citizenship_back_path', sa.String(), nullable=True))
    op.add_column('birth_registration', sa.Column('hospital_birth_certificate_path', sa.String(), nullable=True))
    op.add_column('birth_registration', sa.Column('vaccination_card_path', sa.String(), nullable=True))
    op.add_column('death_registration', sa.Column('deceased_citizenship_front_path', sa.String(), nullable=True))
    op.add_column('death_registration', sa.Column('deceased_citizenship_back_path', sa.String(), nullable=True))
    op.add_column('death_registration', sa.Column('informant_citizenship_front_path', sa.String(), nullable=True))
    op.add_column('death_registration', sa.Column('informant_citizenship_back_path', sa.String(), nullable=True))
    op.add_column('death_registration', sa.Column('hospital_death_report_path', sa.String(), nullable=True))
    op.add_column('death_registration', sa.Column('police_report_path', sa.String(), nullable=True))
    op.add_column('migration_registration', sa.Column('applicant_citizenship_front_path', sa.String(), nullable=True))
    op.add_column('migration_registration', sa.Column('applicant_citizenship_back_path', sa.String(), nullable=True))
    op.add_column('migration_registration', sa.Column('address_proof_path', sa.String(), nullable=True))
    op.add_column('migration_registration', sa.Column('destination_proof_path', sa.String(), nullable=True))
    op.add_column('migration_registration', sa.Column('applicant_photo_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('migration_registration', 'applicant_photo_path')
    op.drop_column('migration_registration', 'destination_proof_path')
    op.drop_column('migration_registration', 'address_proof_path')
    op.drop_column('migration_registration', 'applicant_citizenship_back_path')
    op.drop_column('migration_registration', 'applicant_citizenship_front_path')
    op.drop_column('death_registration', 'police_report_path')
    op.drop_column('death_registration', 'hospital_death_report_path')
    op.drop_column('death_registration', 'informant_citizenship_back_path')
    op.drop_column('death_registration', 'informant_citizenship_front_path')
    op.drop_column('death_registration', 'deceased_citizenship_back_path')
    op.drop_column('death_registration', 'deceased_citizenship_front_path')
    op.drop_column('birth_registration', 'vaccination_card_path')
    op.drop_column('birth_registration', 'hospital_birth_certificate_path')
    op.drop_column('birth_registration', 'mother_citizenship_back_path')
    op.drop_column('birth_registration', 'mother_citizenship_front_path')
    op.drop_column('birth_registration', 'father_citizenship_back_path')
    op.drop_column('birth_registration', 'father_citizenship_front_path')
    # ### end Alembic commands ###
