"""migration certificate

Revision ID: 5e46ba75914e
Revises: e7e2400a8421
Create Date: 2026-07-18 12:41:00.064184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e46ba75914e'
down_revision: Union[str, Sequence[str], None] = 'e7e2400a8421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deceased', sa.Column('deceased_dob_ad', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deceased', 'deceased_dob_ad')
    # ### end Alembic commands ###
