"""notice update image

Revision ID: 6234feb5ae40
Revises: e10eca6dfa12
Create Date: 2026-07-12 23:51:04.900314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6234feb5ae40'
down_revision: Union[str, Sequence[str], None] = 'e10eca6dfa12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('notice_image_path', sa.String(), nullable=True))
    op.add_column('notices', sa.Column('notice_attachment_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'notice_attachment_type')
    op.drop_column('notices', 'notice_image_path')
    # ### end Alembic commands ###
