"""add complain

Revision ID: 62bab804c0e8
Revises: d2aa3189a036
Create Date: 2026-07-26 16:52:53.071188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62bab804c0e8'
down_revision: Union[str, Sequence[str], None] = 'd2aa3189a036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('complaint_number', sa.String(length=20), nullable=False),
    sa.Column('complaint_ward_id', sa.UUID(), nullable=False),
    sa.Column('complaint_submitted_by', sa.Integer(), nullable=False),
    sa.Column('complaint_assigned_to', sa.Integer(), nullable=True),
    sa.Column('complaint_category', sa.Enum('INFRASTRUCTURE', 'SERVICE_DELAY', 'STAFF_MISCONDUCT', 'CORRUPTION', 'WATER_SUPPLY', 'SANITATION', 'OTHER', name='complaintcategory'), nullable=False),
    sa.Column('complaint_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'FORWARDED', 'RESOLVED', 'REJECTED', 'ESCALATED', name='complaintstatus'), nullable=False),
    sa.Column('complaint_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='complaintpriority'), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('attachment_1_path', sa.String(), nullable=True),
    sa.Column('attachment_2_path', sa.String(), nullable=True),
    sa.Column('attachment_3_path', sa.String(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('is_escalated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['complaint_assigned_to'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_submitted_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_ward_id'], ['ward.ward_id'], ),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_index(op.f('ix_complaint_complaint_number'), 'complaint', ['complaint_number'], unique=True)
    op.create_table('complaint_reject',
    sa.Column('reject_id', sa.UUID(), nullable=False),
    sa.Column('reject_text', sa.Text(), nullable=True),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaint.complaint_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('reject_id')
    )
    op.create_table('complaint_remark',
    sa.Column('remark_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_role', sa.Enum('CITIZEN', 'OFFICER', 'SECRETARY', 'CHAIRPERSON', name='authorrole'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaint.complaint_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('remark_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint_remark')
    op.drop_table('complaint_reject')
    op.drop_index(op.f('ix_complaint_complaint_number'), table_name='complaint')
    op.drop_table('complaint')
    # ### end Alembic commands ###
