"""message

Revision ID: 62ecf65fd7be
Revises: 22fb371af575
Create Date: 2026-08-04 02:21:41.000814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62ecf65fd7be'
down_revision: Union[str, Sequence[str], None] = '22fb371af575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_payment', 'receipt_issued_at')
    op.drop_column('tax_payment', 'data_hash')
    op.drop_column('tax_payment', 'qr_path')
    op.drop_column('tax_payment', 'pdf_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_payment', sa.Column('pdf_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tax_payment', sa.Column('qr_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tax_payment', sa.Column('data_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('tax_payment', sa.Column('receipt_issued_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
