"""remove realtionship in birth

Revision ID: 6b700695cc84
Revises: 943de6ffd001
Create Date: 2026-06-16 23:04:30.378290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b700695cc84'
down_revision: Union[str, Sequence[str], None] = '943de6ffd001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ward', sa.Column('ward_municipality', sa.String(length=100), nullable=False))
    op.add_column('ward', sa.Column('ward_district', sa.String(length=100), nullable=False))
    op.drop_column('ward', 'word_municipality')
    op.drop_column('ward', 'word_district')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ward', sa.Column('word_district', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('ward', sa.Column('word_municipality', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('ward', 'ward_district')
    op.drop_column('ward', 'ward_municipality')
    # ### end Alembic commands ###
