"""add tax 7

Revision ID: 7eddfe9db6e3
Revises: 59a6def0cc49
Create Date: 2026-08-02 20:51:40.292928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eddfe9db6e3'
down_revision: Union[str, Sequence[str], None] = '59a6def0cc49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_payment', sa.Column('pidx', sa.String(length=100), nullable=True))
    op.add_column('tax_payment', sa.Column('gateway_status', sa.String(length=50), nullable=True))
    op.add_column('tax_payment', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'tax_payment', ['pidx'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tax_payment', type_='unique')
    op.drop_column('tax_payment', 'transaction_id')
    op.drop_column('tax_payment', 'gateway_status')
    op.drop_column('tax_payment', 'pidx')
    # ### end Alembic commands ###
