"""upgrad fjas

Revision ID: 93cdd777e7c9
Revises: 4495f18bfb13
Create Date: 2026-06-18 14:11:30.374377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93cdd777e7c9'
down_revision: Union[str, Sequence[str], None] = '4495f18bfb13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

new_enum = postgresql.ENUM(
    "DRAFT",
    "SUBMITTED",
    "DOCUMENT_REQUESTED",
    "APPROVED",
    "CERTIFICATE_ISSUED",
    "REJECTED",
    name="birthregistrationstatus",
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    new_enum.create(bind, checkfirst=True)

    op.alter_column(
        "birth_registration",
        "register_status",
        existing_type=postgresql.ENUM(
            "Pending",
            "Approved",
            "Rejected",
            name="registrationstatus",
        ),
        type_=new_enum,
        postgresql_using="""
            CASE register_status
                WHEN 'Pending' THEN 'SUBMITTED'
                WHEN 'Approved' THEN 'APPROVED'
                WHEN 'Rejected' THEN 'REJECTED'
            END::birthregistrationstatus
        """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
