"""remove realtionship user2 

Revision ID: 9b2cefca9d60
Revises: dfb843cdad9f
Create Date: 2026-06-16 23:13:53.322074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2cefca9d60'
down_revision: Union[str, Sequence[str], None] = 'dfb843cdad9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('registration_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'address', 'birth_registration', ['registration_id'], ['registration_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'registration_id')
    # ### end Alembic commands ###
