"""add tax

Revision ID: 9f37bba17734
Revises: 751665bdb53c
Create Date: 2026-08-02 02:24:59.876752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f37bba17734'
down_revision: Union[str, Sequence[str], None] = '751665bdb53c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaint', 'complaint_status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'VERIFIED', 'RESOLVED', 'REJECTED', name='complaintstatus'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaint', 'complaint_status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'VERIFIED', 'RESOLVED', 'REJECTED', name='complaintstatus'),
               server_default=sa.text("'SUBMITTED'::complaintstatus"),
               existing_nullable=False)
    # ### end Alembic commands ###
