"""description_of_changes

Revision ID: adc23acfa545
Revises: 193bfe9922bb
Create Date: 2026-06-20 20:14:52.389659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc23acfa545'
down_revision: Union[str, Sequence[str], None] = '193bfe9922bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ward_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'ward', ['ward_id'], ['ward_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'ward_id')
    # ### end Alembic commands ###
