"""update ward

Revision ID: b65b116cdaa9
Revises: 3327b58540ce
Create Date: 2026-07-09 02:19:40.233470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65b116cdaa9'
down_revision: Union[str, Sequence[str], None] = '3327b58540ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ward', sa.Column('ward_nepali_name', sa.String(), nullable=True))
    op.add_column('ward', sa.Column('ward_nepali_municipality', sa.String(length=100), nullable=True))
    op.add_column('ward', sa.Column('ward_nepali_district', sa.String(length=100), nullable=True))
    op.add_column('ward', sa.Column('ward_nepali_province', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ward', 'ward_nepali_province')
    op.drop_column('ward', 'ward_nepali_district')
    op.drop_column('ward', 'ward_nepali_municipality')
    op.drop_column('ward', 'ward_nepali_name')
    # ### end Alembic commands ###
