"""recommendation add

Revision ID: b80957016645
Revises: 5cb72f74907a
Create Date: 2026-07-24 18:42:07.730524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80957016645'
down_revision: Union[str, Sequence[str], None] = '5cb72f74907a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_letter',
    sa.Column('letter_id', sa.UUID(), nullable=False),
    sa.Column('register_ward_id', sa.UUID(), nullable=False),
    sa.Column('register_submitted_by', sa.Integer(), nullable=False),
    sa.Column('register_status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='recommendationstatus'), nullable=False),
    sa.Column('letter_type', sa.Enum('RESIDENCE_PROOF', 'UNMARRIED_STATUS', 'CHARACTER_CERTIFICATE', 'INCOME_STATEMENT', 'RELATIONSHIP_PROOF', 'LAND_OWNERSHIP_PROOF', 'OTHER', name='recommendationlettertype'), nullable=False),
    sa.Column('letter_type_other', sa.String(length=200), nullable=True),
    sa.Column('applicant_full_name_np', sa.String(length=200), nullable=False),
    sa.Column('applicant_full_name_en', sa.String(length=200), nullable=False),
    sa.Column('applicant_citizenship_no', sa.String(length=50), nullable=False),
    sa.Column('applicant_contact_no', sa.String(length=50), nullable=True),
    sa.Column('applicant_province', sa.String(length=100), nullable=True),
    sa.Column('applicant_district', sa.String(length=100), nullable=True),
    sa.Column('applicant_municipality', sa.String(length=100), nullable=True),
    sa.Column('applicant_ward_number', sa.Integer(), nullable=True),
    sa.Column('applicant_tole', sa.String(length=200), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('applicant_citizenship_path', sa.String(), nullable=True),
    sa.Column('supporting_document_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['register_submitted_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['register_ward_id'], ['ward.ward_id'], ),
    sa.PrimaryKeyConstraint('letter_id')
    )
    op.create_table('recommendation_certificate',
    sa.Column('cert_id', sa.UUID(), nullable=False),
    sa.Column('letter_id', sa.UUID(), nullable=False),
    sa.Column('certificate_no', sa.String(length=100), nullable=False),
    sa.Column('data_hash', sa.String(length=64), nullable=False),
    sa.Column('qr_path', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['issued_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['letter_id'], ['recommendation_letter.letter_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cert_id'),
    sa.UniqueConstraint('certificate_no'),
    sa.UniqueConstraint('letter_id')
    )
    op.create_table('recommendation_reject',
    sa.Column('reject_id', sa.UUID(), nullable=False),
    sa.Column('reject_text', sa.Text(), nullable=True),
    sa.Column('letter_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['letter_id'], ['recommendation_letter.letter_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reject_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_reject')
    op.drop_table('recommendation_certificate')
    op.drop_table('recommendation_letter')
    # ### end Alembic commands ###
