"""Initial migration

Revision ID: bcab25d3982d
Revises: 97bae1f2240e
Create Date: 2026-07-11 20:08:58.695243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcab25d3982d'
down_revision: Union[str, Sequence[str], None] = '97bae1f2240e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('cert_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('certificate_no', sa.String(length=100), nullable=False),
    sa.Column('data_hash', sa.String(length=64), nullable=False),
    sa.Column('qr_path', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['issued_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cert_id'),
    sa.UniqueConstraint('certificate_no'),
    sa.UniqueConstraint('registration_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate')
    # ### end Alembic commands ###
