"""deathregistration update

Revision ID: ca936109ab72
Revises: 40cd7c4dd181
Create Date: 2026-07-16 19:37:31.396444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca936109ab72'
down_revision: Union[str, Sequence[str], None] = '40cd7c4dd181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('death_registration',
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('register_ward_id', sa.UUID(), nullable=False),
    sa.Column('register_submitted_by', sa.Integer(), nullable=False),
    sa.Column('register_status', sa.Enum('DRAFT', 'SUBMITTED', 'DOCUMENT_REQUESTED', 'APPROVED', 'CERTIFICATE_ISSUED', 'REJECTED', 'VERIFIED', name='deathregistrationstatus', create_type=False), nullable=False),
    sa.Column('registration_no', sa.String(length=50), nullable=True),
    sa.Column('page_no', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['register_submitted_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['register_ward_id'], ['ward.ward_id'], ),
    sa.PrimaryKeyConstraint('registration_id')
    )
    op.create_table('death_address',
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('deceased_province', sa.String(), nullable=True),
    sa.Column('deceased_district', sa.String(), nullable=True),
    sa.Column('deceased_municipality', sa.String(), nullable=True),
    sa.Column('deceased_ward_number', sa.Integer(), nullable=True),
    sa.Column('deceased_tole', sa.String(), nullable=True),
    sa.Column('death_place_province', sa.String(), nullable=True),
    sa.Column('death_place_district', sa.String(), nullable=True),
    sa.Column('death_place_municipality', sa.String(), nullable=True),
    sa.Column('death_place_ward_number', sa.Integer(), nullable=True),
    sa.Column('death_place_tole', sa.String(), nullable=True),
    sa.Column('informant_province', sa.String(), nullable=True),
    sa.Column('informant_district', sa.String(), nullable=True),
    sa.Column('informant_municipality', sa.String(), nullable=True),
    sa.Column('informant_ward_number', sa.Integer(), nullable=True),
    sa.Column('informant_tole', sa.String(), nullable=True),
    sa.Column('ward_nepali_name', sa.String(), nullable=True),
    sa.Column('ward_nepali_municipality', sa.String(length=100), nullable=True),
    sa.Column('ward_nepali_district', sa.String(length=100), nullable=True),
    sa.Column('ward_nepali_province', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['death_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('death_certificate',
    sa.Column('cert_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('certificate_no', sa.String(length=100), nullable=False),
    sa.Column('data_hash', sa.String(length=64), nullable=False),
    sa.Column('qr_path', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['issued_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_id'], ['death_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cert_id'),
    sa.UniqueConstraint('certificate_no'),
    sa.UniqueConstraint('registration_id')
    )
    op.create_table('death_detail',
    sa.Column('death_detail_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('death_date_bs', sa.DateTime(), nullable=False),
    sa.Column('death_time_period', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', 'NIGHT', name='deathtimeperiodtype', create_type=False), nullable=True),
    sa.Column('death_time', sa.String(length=20), nullable=True),
    sa.Column('death_place_type', sa.Enum('HOME', 'HOSPITAL', 'OTHER', name='deathplacetype', create_type=False), nullable=False),
    sa.Column('death_place_other_detail', sa.String(length=200), nullable=True),
    sa.Column('death_cause', sa.Text(), nullable=True),
    sa.Column('death_type', sa.Enum('NATURAL', 'ACCIDENT', 'SUICIDE', 'HOMICIDE', 'OTHER', name='deathcausetype', create_type=False), nullable=False),
    sa.Column('death_type_other_detail', sa.String(length=200), nullable=True),
    sa.Column('residence_duration_years', sa.Integer(), nullable=True),
    sa.Column('residence_duration_months', sa.Integer(), nullable=True),
    sa.Column('residence_duration_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['death_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('death_detail_id')
    )
    op.create_table('death_reject',
    sa.Column('reject_id', sa.UUID(), nullable=False),
    sa.Column('reject_text', sa.Text(), nullable=True),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['death_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reject_id')
    )
    op.create_table('deceased',
    sa.Column('deceased_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('deceased_first_name', sa.String(length=100), nullable=True),
    sa.Column('deceased_middle_name', sa.String(length=100), nullable=True),
    sa.Column('deceased_last_name', sa.String(length=100), nullable=True),
    sa.Column('deceased_nepali_first_name', sa.String(length=100), nullable=True),
    sa.Column('deceased_nepali_middle_name', sa.String(length=100), nullable=True),
    sa.Column('deceased_nepali_last_name', sa.String(length=100), nullable=True),
    sa.Column('deceased_gender', sa.Enum('MALE', 'FEMALE', 'OTHERS', name='gendertype', create_type=False), nullable=False),
    sa.Column('deceased_dob_bs', sa.DateTime(), nullable=True),
    sa.Column('deceased_age_years', sa.Integer(), nullable=True),
    sa.Column('deceased_age_months', sa.Integer(), nullable=True),
    sa.Column('deceased_age_days', sa.Integer(), nullable=True),
    sa.Column('deceased_marital_status', sa.Enum('UNMARRIED', 'MARRIED', 'WIDOWED', 'OTHER', name='maritalstatustype', create_type=False), nullable=False),
    sa.Column('deceased_citizenship_no', sa.String(length=50), nullable=True),
    sa.Column('deceased_occupation', sa.String(length=100), nullable=True),
    sa.Column('deceased_other_id_no', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['death_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deceased_id')
    )
    op.create_table('informant',
    sa.Column('informant_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('informant_name', sa.String(length=200), nullable=False),
    sa.Column('informant_relationship', postgresql.ENUM('FATHER', 'MOTHER', 'GRANDFATHER', 'GRANDMOTHER', 'GUARDIAN', 'OTHER', name='relatioshiptype', create_type=False), nullable=True),
    sa.Column('informant_contact_no', sa.String(length=50), nullable=True),
    sa.Column('informant_signature_path', sa.String(), nullable=True),
    sa.Column('declared_date_bs', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['death_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('informant_id')
    
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('informant')
    op.drop_table('deceased')
    op.drop_table('death_reject')
    op.drop_table('death_detail')
    op.drop_table('death_certificate')
    op.drop_table('death_address')
    op.drop_table('death_registration')
    # ### end Alembic commands ###