"""update email

Revision ID: cf6c6b72b578
Revises: 32438caf20f2
Create Date: 2026-07-12 18:30:39.686070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf6c6b72b578'
down_revision: Union[str, Sequence[str], None] = '32438caf20f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('nin_no', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'certificate', ['nin_no'])
    op.add_column('users', sa.Column('user_email', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'users', ['user_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_email')
    op.drop_constraint(None, 'certificate', type_='unique')
    op.drop_column('certificate', 'nin_no')
    # ### end Alembic commands ###
