"""recommend up

Revision ID: d2aa3189a036
Revises: cac66c674825
Create Date: 2026-07-25 18:37:28.092927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2aa3189a036'
down_revision: Union[str, Sequence[str], None] = 'cac66c674825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_letter', sa.Column('ward_nepali_province', sa.String(length=100), nullable=True))
    op.add_column('recommendation_letter', sa.Column('ward_nepali_district', sa.String(length=100), nullable=True))
    op.add_column('recommendation_letter', sa.Column('ward_nepali_municipality', sa.String(length=100), nullable=True))
    op.add_column('recommendation_letter', sa.Column('ward_nepali_name', sa.String(length=100), nullable=True))
    op.add_column('recommendation_letter', sa.Column('ward_type', sa.String(length=50), nullable=True))
    op.add_column('recommendation_letter', sa.Column('applicant_citizenship_front_path', sa.String(), nullable=True))
    op.add_column('recommendation_letter', sa.Column('applicant_citizenship_back_path', sa.String(), nullable=True))
    op.drop_column('recommendation_letter', 'applicant_citizenship_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_letter', sa.Column('applicant_citizenship_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('recommendation_letter', 'applicant_citizenship_back_path')
    op.drop_column('recommendation_letter', 'applicant_citizenship_front_path')
    op.drop_column('recommendation_letter', 'ward_type')
    op.drop_column('recommendation_letter', 'ward_nepali_name')
    op.drop_column('recommendation_letter', 'ward_nepali_municipality')
    op.drop_column('recommendation_letter', 'ward_nepali_district')
    op.drop_column('recommendation_letter', 'ward_nepali_province')
    # ### end Alembic commands ###
