"""initial_clean_setup

Revision ID: d4bab5ea20c9
Revises: 
Create Date: 2026-06-13 23:58:47.452327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4bab5ea20c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reject',
    sa.Column('reject_id', sa.UUID(), nullable=False),
    sa.Column('reject_text', sa.Text(), nullable=True),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reject_id')
    )
    op.drop_table('certificate')
    op.drop_table('workflow_log')
    op.drop_table('user_account')
    op.drop_table('informant')
    op.drop_table('address')
    op.drop_table('document')
    op.add_column('birth_registration', sa.Column('register_ward_id', sa.UUID(), nullable=False))
    op.add_column('birth_registration', sa.Column('register_submitted_by', sa.UUID(), nullable=False))
    op.add_column('birth_registration', sa.Column('register_status', sa.Enum('DRAFT', 'SUBMITTED', 'DOCUMENT_REQUESTED', 'APPROVED', 'CERTIFICATE_ISSUED', 'REJECTED', name='registrationstatus'), nullable=False))
    op.alter_column('birth_registration', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('birth_registration', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('birth_registration_registration_number_key'), 'birth_registration', type_='unique')
    op.drop_constraint(op.f('birth_registration_submitted_by_fkey'), 'birth_registration', type_='foreignkey')
    op.drop_constraint(op.f('birth_registration_ward_id_fkey'), 'birth_registration', type_='foreignkey')
    op.create_foreign_key(None, 'birth_registration', 'ward', ['register_ward_id'], ['ward_id'])
    op.create_foreign_key(None, 'birth_registration', 'users', ['register_submitted_by'], ['user_id'], ondelete='SET NULL')
    op.drop_column('birth_registration', 'status')
    op.drop_column('birth_registration', 'fine_paid')
    op.drop_column('birth_registration', 'verified_at')
    op.drop_column('birth_registration', 'ward_id')
    op.drop_column('birth_registration', 'submitted_by')
    op.drop_column('birth_registration', 'fine_amount')
    op.drop_column('birth_registration', 'rejection_reason')
    op.drop_column('birth_registration', 'is_late_registration')
    op.drop_column('birth_registration', 'issued_at')
    op.drop_column('birth_registration', 'registration_number')
    op.drop_column('birth_registration', 'submitted_at')
    op.add_column('child', sa.Column('child_full_name', sa.String(length=100), nullable=True))
    op.add_column('child', sa.Column('child_gender', sa.Enum('MALE', 'FEMALE', 'OTHERS', name='gendertype'), nullable=False))
    op.add_column('child', sa.Column('child_dob_bs', sa.String(length=50), nullable=False))
    op.add_column('child', sa.Column('child_time_of_birth', sa.String(), nullable=True))
    op.add_column('child', sa.Column('child_province', sa.String(length=100), nullable=True))
    op.add_column('child', sa.Column('child_district', sa.String(length=100), nullable=True))
    op.add_column('child', sa.Column('child_municipality', sa.String(length=100), nullable=True))
    op.add_column('child', sa.Column('child_ward_no', sa.Integer(), nullable=True))
    op.add_column('child', sa.Column('child_birth_kind', sa.Enum('SINGLE', 'TWIN', 'TRIPLET_OR_MORE', name='birthkindtype'), nullable=False))
    op.add_column('child', sa.Column('child_weight_kg', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('child_registration_id_key'), 'child', type_='unique')
    op.drop_column('child', 'gender')
    op.drop_column('child', 'weight_kg')
    op.drop_column('child', 'dob_bs')
    op.drop_column('child', 'time_of_birth')
    op.drop_column('child', 'district')
    op.drop_column('child', 'birth_kind')
    op.drop_column('child', 'full_name')
    op.drop_column('child', 'tole')
    op.drop_column('child', 'municipality')
    op.drop_column('child', 'ward_no')
    op.drop_column('child', 'province')
    op.drop_column('child', 'dob_ad')
    op.add_column('nominee', sa.Column('nominee_registration_id', sa.UUID(), nullable=True))
    op.add_column('nominee', sa.Column('nominee_full_name', sa.String(length=100), nullable=True))
    op.add_column('nominee', sa.Column('nominee_citizenship_no', sa.String(length=50), nullable=True))
    op.add_column('nominee', sa.Column('nominee_address', sa.Text(), nullable=True))
    op.add_column('nominee', sa.Column('nominee_contact_no', sa.String(length=20), nullable=True))
    op.add_column('nominee', sa.Column('nominee_witness_order', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_witness_per_registration'), 'nominee', type_='unique')
    op.drop_constraint(op.f('nominee_registration_id_fkey'), 'nominee', type_='foreignkey')
    op.create_foreign_key(None, 'nominee', 'birth_registration', ['nominee_registration_id'], ['registration_id'])
    op.drop_column('nominee', 'registration_id')
    op.drop_column('nominee', 'citizenship_no')
    op.drop_column('nominee', 'full_name')
    op.drop_column('nominee', 'contact_no')
    op.drop_column('nominee', 'witness_order')
    op.drop_column('nominee', 'address')
    op.add_column('parent', sa.Column('parrent_citizenship_no', sa.String(length=50), nullable=False))
    op.add_column('parent', sa.Column('parent_nid_no', sa.String(length=50), nullable=False))
    op.add_column('parent', sa.Column('parent_occupation', sa.String(length=100), nullable=True))
    op.add_column('parent', sa.Column('parent_nationality', sa.String(length=100), nullable=False))
    op.add_column('parent', sa.Column('parent_contact_no', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('uq_parent_per_registration'), 'parent', type_='unique')
    op.drop_constraint(op.f('parent_address_id_fkey'), 'parent', type_='foreignkey')
    op.drop_column('parent', 'citizenship_no')
    op.drop_column('parent', 'nationality')
    op.drop_column('parent', 'nid_no')
    op.drop_column('parent', 'occupation')
    op.drop_column('parent', 'contact_no')
    op.drop_column('parent', 'address_id')
    op.add_column('ward', sa.Column('word_municipality', sa.String(length=100), nullable=False))
    op.add_column('ward', sa.Column('word_district', sa.String(length=100), nullable=False))
    op.add_column('ward', sa.Column('ward_province', sa.String(length=50), nullable=False))
    op.add_column('ward', sa.Column('ward_contact_number', sa.String(length=50), nullable=False))
    op.add_column('ward', sa.Column('ward_email', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('ward_email_key'), 'ward', type_='unique')
    op.create_unique_constraint(None, 'ward', ['ward_email'])
    op.drop_column('ward', 'registrar_name')
    op.drop_column('ward', 'contact_number')
    op.drop_column('ward', 'district')
    op.drop_column('ward', 'email')
    op.drop_column('ward', 'municipality')
    op.drop_column('ward', 'province')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ward', sa.Column('province', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('ward', sa.Column('municipality', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('ward', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ward', sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('ward', sa.Column('contact_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('ward', sa.Column('registrar_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ward', type_='unique')
    op.create_unique_constraint(op.f('ward_email_key'), 'ward', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('ward', 'ward_email')
    op.drop_column('ward', 'ward_contact_number')
    op.drop_column('ward', 'ward_province')
    op.drop_column('ward', 'word_district')
    op.drop_column('ward', 'word_municipality')
    op.add_column('parent', sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('parent', sa.Column('contact_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('parent', sa.Column('occupation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('parent', sa.Column('nid_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('parent', sa.Column('nationality', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('parent', sa.Column('citizenship_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('parent_address_id_fkey'), 'parent', 'address', ['address_id'], ['address_id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('uq_parent_per_registration'), 'parent', ['registration_id', 'parent_type'], postgresql_nulls_not_distinct=False)
    op.drop_column('parent', 'parent_contact_no')
    op.drop_column('parent', 'parent_nationality')
    op.drop_column('parent', 'parent_occupation')
    op.drop_column('parent', 'parent_nid_no')
    op.drop_column('parent', 'parrent_citizenship_no')
    op.add_column('nominee', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('nominee', sa.Column('witness_order', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('nominee', sa.Column('contact_no', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('nominee', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('nominee', sa.Column('citizenship_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('nominee', sa.Column('registration_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'nominee', type_='foreignkey')
    op.create_foreign_key(op.f('nominee_registration_id_fkey'), 'nominee', 'birth_registration', ['registration_id'], ['registration_id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_witness_per_registration'), 'nominee', ['registration_id', 'witness_order'], postgresql_nulls_not_distinct=False)
    op.drop_column('nominee', 'nominee_witness_order')
    op.drop_column('nominee', 'nominee_contact_no')
    op.drop_column('nominee', 'nominee_address')
    op.drop_column('nominee', 'nominee_citizenship_no')
    op.drop_column('nominee', 'nominee_full_name')
    op.drop_column('nominee', 'nominee_registration_id')
    op.add_column('child', sa.Column('dob_ad', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('child', sa.Column('province', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('child', sa.Column('ward_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('child', sa.Column('municipality', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('child', sa.Column('tole', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('child', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('child', sa.Column('birth_kind', postgresql.ENUM('SINGLE', 'TWIN', 'TRIPLET_OR_MORE', name='birthkindtype'), autoincrement=False, nullable=False))
    op.add_column('child', sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('child', sa.Column('time_of_birth', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('child', sa.Column('dob_bs', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('child', sa.Column('weight_kg', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
    op.add_column('child', sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHERS', name='gendertype'), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('child_registration_id_key'), 'child', ['registration_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('child', 'child_weight_kg')
    op.drop_column('child', 'child_birth_kind')
    op.drop_column('child', 'child_ward_no')
    op.drop_column('child', 'child_municipality')
    op.drop_column('child', 'child_district')
    op.drop_column('child', 'child_province')
    op.drop_column('child', 'child_time_of_birth')
    op.drop_column('child', 'child_dob_bs')
    op.drop_column('child', 'child_gender')
    op.drop_column('child', 'child_full_name')
    op.add_column('birth_registration', sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('birth_registration', sa.Column('registration_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('birth_registration', sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('birth_registration', sa.Column('is_late_registration', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('birth_registration', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('birth_registration', sa.Column('fine_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('birth_registration', sa.Column('submitted_by', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('birth_registration', sa.Column('ward_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('birth_registration', sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('birth_registration', sa.Column('fine_paid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('birth_registration', sa.Column('status', postgresql.ENUM('Pending', 'Approved', 'Rejected', name='registrationstatus'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'birth_registration', type_='foreignkey')
    op.drop_constraint(None, 'birth_registration', type_='foreignkey')
    op.create_foreign_key(op.f('birth_registration_ward_id_fkey'), 'birth_registration', 'ward', ['ward_id'], ['ward_id'])
    op.create_foreign_key(op.f('birth_registration_submitted_by_fkey'), 'birth_registration', 'user_account', ['submitted_by'], ['user_id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('birth_registration_registration_number_key'), 'birth_registration', ['registration_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('birth_registration', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('birth_registration', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('birth_registration', 'register_status')
    op.drop_column('birth_registration', 'register_submitted_by')
    op.drop_column('birth_registration', 'register_ward_id')
    op.create_table('document',
    sa.Column('doc_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('registration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doc_type', postgresql.ENUM('CITIZENSHIP_FATHER', 'CITIZENSHIP_MOTHER', 'MARRIAGE_CERT', 'RESIDENCE_PROOF', 'IN_MIGRATION_CERT', name='documenttype'), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('file_size_kb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('verified_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('file_size_kb IS NULL OR file_size_kb > 0', name=op.f('chk_file_size')),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], name=op.f('document_registration_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['user_account.user_id'], name=op.f('document_verified_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('doc_id', name=op.f('document_pkey'))
    )
    op.create_table('address',
    sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('province', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('municipality', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ward_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tole', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('address_id', name=op.f('address_pkey'))
    )
    op.create_table('informant',
    sa.Column('informant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('registration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('citizenship_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_no', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('reported_at_bs', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('reported_at_ad', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], name=op.f('informant_registration_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('informant_id', name=op.f('informant_pkey')),
    sa.UniqueConstraint('registration_id', name=op.f('informant_registration_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_account',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ward_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('user_role', postgresql.ENUM('CITIZEN', 'WARD_OFFICER', 'REGISTRAR', 'ADMIN', name='userroletype'), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ward_id'], ['ward.ward_id'], name=op.f('user_account_ward_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_account_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_account_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('user_account_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('workflow_log',
    sa.Column('log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('registration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status_from', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status_to', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('performed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['user_account.user_id'], name=op.f('workflow_log_performed_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], name=op.f('workflow_log_registration_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id', name=op.f('workflow_log_pkey'))
    )
    op.create_table('certificate',
    sa.Column('cert_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('registration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('certificate_no', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nid_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('issued_date_bs', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('issued_date_ad', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('issued_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('qr_code_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pdf_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_reason IS NOT NULL', name=op.f('chk_revoked_has_reason')),
    sa.ForeignKeyConstraint(['issued_by'], ['user_account.user_id'], name=op.f('certificate_issued_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_id'], ['birth_registration.registration_id'], name=op.f('certificate_registration_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cert_id', name=op.f('certificate_pkey')),
    sa.UniqueConstraint('certificate_no', name=op.f('certificate_certificate_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('registration_id', name=op.f('certificate_registration_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('reject')
    # ### end Alembic commands ###
