"""update nepal

Revision ID: e10eca6dfa12
Revises: e75888ad7bf3
Create Date: 2026-07-12 21:27:09.982227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10eca6dfa12'
down_revision: Union[str, Sequence[str], None] = 'e75888ad7bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_verify', sa.Column('user_email', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'users_verify', ['user_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_verify', type_='unique')
    op.drop_column('users_verify', 'user_email')
    # ### end Alembic commands ###
