"""neplai nmae user

Revision ID: e75888ad7bf3
Revises: cf6c6b72b578
Create Date: 2026-07-12 21:02:36.485400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75888ad7bf3'
down_revision: Union[str, Sequence[str], None] = 'cf6c6b72b578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_nepali_name', sa.String(length=150), nullable=True))
    op.add_column('users_verify', sa.Column('user_nepali_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_verify', 'user_nepali_name')
    op.drop_column('users', 'user_nepali_name')
    # ### end Alembic commands ###
