"""verify change

Revision ID: ed145a84f00a
Revises: adc23acfa545
Create Date: 2026-06-21 00:33:46.081964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed145a84f00a'
down_revision: Union[str, Sequence[str], None] = 'adc23acfa545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_verify', sa.Column('ward_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users_verify', 'ward', ['ward_id'], ['ward_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_verify', type_='foreignkey')
    op.drop_column('users_verify', 'ward_id')
    # ### end Alembic commands ###
