"""add nepali address fields and occupation type to migration

Revision ID: f739b63885c0
Revises: 067a4da377ff
Create Date: 2026-07-27 06:20:18.453444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f739b63885c0'
down_revision: Union[str, Sequence[str], None] = '067a4da377ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Declare the Enum type object
occupation_enum = postgresql.ENUM(
    'FARMER', 'SERVICE', 'BUSINESS', 'STUDENT', 
    'LABOUR', 'HOUSEWIFE', 'UNEMPLOYED', 'OTHER', 
    name='occupationtype'
)


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Explicitly create the Postgres ENUM type first
    occupation_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migration_address', sa.Column('province_np', sa.String(length=100), nullable=True))
    op.add_column('migration_address', sa.Column('district_np', sa.String(length=100), nullable=True))
    op.add_column('migration_address', sa.Column('municipality_np', sa.String(length=100), nullable=True))
    op.add_column('migration_address', sa.Column('ward_name_np', sa.String(length=200), nullable=True))
    op.add_column('migration_applicant', sa.Column('aapplicant_occupation', occupation_enum, nullable=True))
    op.drop_column('migration_applicant', 'applicant_occupation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migration_applicant', sa.Column('applicant_occupation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('migration_applicant', 'aapplicant_occupation')
    op.drop_column('migration_address', 'ward_name_np')
    op.drop_column('migration_address', 'municipality_np')
    op.drop_column('migration_address', 'district_np')
    op.drop_column('migration_address', 'province_np')
    # ### end Alembic commands ###

    # 2. Clean up and drop the ENUM type when rolling back
    occupation_enum.drop(op.get_bind(), checkfirst=True)