"""add child nepali name columns

Revision ID: f9f0e44203e7
Revises: 87a3f594e25c
Create Date: 2026-07-07 19:52:27.041290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f0e44203e7'
down_revision: Union[str, Sequence[str], None] = '87a3f594e25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'birth_registration', 'users', ['register_submitted_by'], ['user_id'], ondelete='SET NULL')
    op.add_column('child', sa.Column('child_nepali_first_name', sa.String(length=100), nullable=True))
    op.add_column('child', sa.Column('child_nepali_middle_name', sa.String(length=100), nullable=True))
    op.add_column('child', sa.Column('child_nepali_last_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child', 'child_nepali_last_name')
    op.drop_column('child', 'child_nepali_middle_name')
    op.drop_column('child', 'child_nepali_first_name')
    op.drop_constraint(None, 'birth_registration', type_='foreignkey')
    # ### end Alembic commands ###
